keywords.txt
src/BLEStringCharacteristic.cpp
src/BLEStringCharacteristic.h

Resolves #4.
Example usage sketch:
```arduino
BLEService stringService("19B10000-0001-537E-4F6C-D104768A1214"); // BLE String Service
BLEStringCharacteristic stringCharacteristic("19B10001-0001-537E-4F6C-D104768A1214", BLERead | BLEWrite, 512);
void setup() {
Serial.begin(9600);
while (!Serial);
// begin initialization
if (!BLE.begin()) {
Serial.println("starting BLE failed!");
while (1);
}
// set advertised local name and service UUID:
BLE.setLocalName("String");
BLE.setAdvertisedService(stringService);
// add the characteristic to the service
stringService.addCharacteristic(stringCharacteristic);
// add service
BLE.addService(stringService);
// set the initial value for the characeristic:
stringCharacteristic.writeValue("hello");
// start advertising …
```

Add new BLEStringCharacateristic type

---

src/local/BLELocalCharacteristic.h

Characteristic value lengths can be up to 512 bytes, uint8_t should not be used to store the length

---

src/utility/HCICordioTransport.cpp
src/utility/HCICordioTransport.h

@8bitkick, found that not calling `BLE.begin()` before `BLE.advertise()` made things crash on the Arduino Nano 33 BLE.
This change makes things more resilient.

Cordio: prevent crashes if BLE.begin() is not called

---

src/utility/HCI.cpp
src/utility/HCI.h

@tigoe this should address the issue you were seeing with two Arduino boards (central + peripheral), when one board had more than one 128-bit UUID characteristic per service.
The root cause is the Bluetooth HCI link controller work fragment incoming ACL packets, so I've added an internal buffer to handle this scenario.

Handle ACL RX packet fragementation via buffer

---

src/BLECharacteristic.cpp
src/remote/BLERemoteCharacteristic.cpp
src/remote/BLERemoteCharacteristic.h

Observed by @tigoe, if a notification was received, and the characteristic was readable an unnecessary read request is sent (and value updated would be reset to true as well).
These changes correct this behaviour.

Fix BLECharacteristic::readValue(...) triggering a read request after a notification/indication was received

---

src/BLECharacteristic.cpp
src/BLEDevice.cpp
src/BLEService.cpp
src/utility/ATT.cpp
src/utility/GAP.cpp

Use case insensitive comparison for UUID or address string inputs

---

src/local/BLELocalDevice.cpp
src/local/BLELocalDevice.h
src/utility/GAP.cpp
src/utility/GAP.h

ArduinoBLE referense sample code
```
byte data[5] = { 0x01, 0x02, 0x03, 0x04, 0x05};
BLE.setManufacturerData(data, 5);
```
Result of code execution
0x0201 -> companyId
0x03, 0x04, 0x05 -> manufacturerData
I think it ’s very confusing.
BLE.setManufacturerData(uint8_ uint8_t manufacturerData[], int manufacturerDataLength)
↓
BLE.setManufacturerData(**const uint16_t companyId**, const uint8_t manufacturerData[], int manufacturerDataLength)
```
uint8_t data[5] = { 0x01, 0x02, 0x03, 0x04, 0x05};
BLE.setManufacturerData(0x1234, data, 5);
```
0x1234 -> companyId
0x01, 0x02, 0x03, 0x04, 0x05 -> manufacturerData

Add (optional) company ID argument to BLE.setManufacturerData(....)

---

src/utility/HCICordioTransport.cpp

I've been testing this with the `Examples -> Peripheral -> LEDCallback` example, with two changes:
1) Removing: `while (!Serial);` from `setup()`
2) Changing `BLE.poll();` in `loop()` to `BLE.poll(60000);`
Unfortunately, in my brief testing it doesn't seem to be lower power (using a USB supply input).
@facchinm any thoughts on this?

cordio: lower power polling with timeout

---

src/utility/HCICordioTransport.cpp

This resolves #33.
This pull request has two changes:
1) It calls `timer.start()` in the BLE thread loop. Without this, `timer.read_high_resolution_us()` always returns 0.
**Note:** the issue is also present in the mbed sample code the HCI transport was based on: https://github.com/ARMmbed/mbed-os-cordio-hci-passthrough/blob/fix-wsf-msg/main.cpp#L86 (@facchinm should we inform them?)
2) It reverts part of pull request #15. Unfortunately, the `WSF_MS_PER_TICK` needs to match the value mbed was compiled with for the supervision timeout to match: https://github.com/ARMmbed/mbed-os/blob/19e762298f9a020606f7358539bb653be0de8e4f/features/FEATURE_BLE/targets/TARGET_CORDIO_LL/stack/controller/sources/ble/lctr/lctr_main_conn.c#L1168-L1174
@facchinm I think we should measure the power consumption …

Cordio: BLE thread loop fixes

---

src/utility/GAP.cpp

Fixes https://github.com/arduino-libraries/ArduinoBLE/issues/56
Right now, `setAdvertisedService()` shadows `setManufacturerData()` if called in the sketch (due to the `else if` statement).
Commit e83c3ce prepares for the coexistence but I have to read the specs a bit more before having it enabled.

setManufacturerData: allocate tmpManufacturerData in the heap

---

src/utility/HCICordioTransport.cpp

Fixes https://github.com/arduino-libraries/ArduinoBLE/issues/65

CordioHCILoop: properly terminate bleLoop thread

---

src/utility/ATT.cpp

3.4.1.1 of ATT protocol spec suggests that in the ATT_ERROR_RSP, the Request Opcode In Error should be set to the request that generated the error.  In this case it looks like it should actually be  ATT_FIND_BY_TYPE_VALUE_REQ (ATT_OP_READ_BY_GROUP_REQ)

PDU rejected due to wrong opcode set in 'Request Opcode In Error'

---

src/utility/GAP.cpp

Test sketch:
```
BLEService myService("fff0");
BLEIntCharacteristic myCharacteristic("fff1", BLERead | BLEBroadcast);
int count = 0;
void setup() {
Serial.begin(9600);
while (!Serial);
if (!BLE.begin()) {
Serial.println("failed to initialize BLE!");
while (1);
}
myService.addCharacteristic(myCharacteristic);
BLE.addService(myService);
BLE.setAdvertisedService(myService);
BLE.advertise();
Serial.println("advertising ...");
myCharacteristic.broadcast();
}
void loop() {
BLE.poll();
count++;
myCharacteristic.writeValue(count);
delay(100);
}
```

Fix for advertised service data not working

---

src/utility/ATT.cpp

The 'nextCharacteristic' selection was wrong.
Thus, when using nextCharacteristic for taking the end handle for the request, the end handle of the current characteristic was taken.
This resulted in the following condition to be true: (reqStartHandle > reqEndHandle)
For such reason, in many cases the descriptors were not retrieved. Specifically, all the characteristics of a service, except the last one, will result without descriptors.
This will result in an error where trying to subscribe to a characteristic which has a descriptor before the CCCD one. (for instance the User Description Descriptor)
In case the subscription is made on a characteristic having the CCCD as first descriptor there are no errors, because if no descriptors are found the write request, needed for the subscription, …

Fix discovery of descriptors

---

src/utility/HCICordioTransport.cpp

The mbed ble stack is initialized at the beginning in order to exploit the service pack transfer.
Once it has been initialized, the queue used to dispatch the ble events is stopped.
At this point the mbed stack is no more used and ArduinoBLE exploits directly the low level uart transport layer.

[portenta] Send service pack updates through mbed initialization

---

src/utility/GATT.cpp
src/utility/GATT.h

Default local characteristics and services are now allocated in the HEAP.
This change is needed for CI integration. Indeed, if these attributes are allocated in the STACK they cannot be freed by the 'delete' statement actually called by their destructors.
Downside: being allocated in the HEAP, their memory usage will not be counted in the estimated amount of RAM occupied by a resulting program that includes this library.

Change allocation of default services and characteristics

---

library.properties

Hey all,
We recently added support for this library on our artemis board which have an apollo3 core. No changes needed other than updating architectures list to include these boards.

Add apollo3 core support

---

.github/workflows/spell-check.yml

After #122, CI unit testing with Catch2 is supported for this library. The spell-check action was failing due to some checks in the catch2 libraries, like in this [example](https://github.com/arduino-libraries/ArduinoBLE/pull/131/checks?check_run_id=1331198955).
This patch will allow to ignore the extras/test folder during the execution of this action and avoid these failures.

Update spell-check action and skip extras/test path

---

src/local/BLELocalDevice.cpp
src/local/BLELocalDevice.h

API functions to set the parameters of advertising data return a bool value:
-  'true' -> advertising parameter is correctly set
-  'false' -> advertising parameter is not set, there is not enough space in the packet to advertise it
<br>
Example sketch:
<br><br>
_Using standard advertising method_
```C++
// Advertising parameters should have a global scope. Do NOT define them in 'setup' or in 'loop'
const uint8_t manufactData[4] = {0};
const uint8_t manufactDataLong[30] = {0};
void setup() 
{
Serial.begin(9600);
while (!Serial);
if (!BLE.begin()) {
Serial.println("failed to initialize BLE!");
while (1);
}
bool success = BLE.setLocalName("Test advertising return type");
if (!success) { Serial.println("Failed to set parameter, not enough space available"); }
// Try …
```

API: set advertising param functions return success

---

extras/arduino-ble-parser.py

This python script allows to encode the Serial debug output into a format that can be analyzed by wireshark and hcidump
Steps to debug:
- modify the sketch attaching Serial to BLE debug 'BLE.debug(Serial)'
- execute the sketch and open the arduino serial monitor
- save the content of the serial monitor in a file (here 'inputFile')
- execute the script with the following arguments: -i to specify the input file, -o to specify the output file
`python your/script/path/arduino-ble-parser.py -i inputFile -o outputFile`
- using wireshark, simply open outputFile

Add python script to make the output of serial debug analyzable through wireshark

---

src/BLEAdvertisingData.cpp

If a BLEAdvertisingData packet has the raw data parameter set, all the other parameters are ignored when encoding the actual data packet.
This means that the raw data parameter can be as long as the maximum length for an advertising packet (MAX_AD_DATA_LENGTH), that is 31 bytes as per BLE standard.
During the setting of the raw data parameter: if the passed raw data length is larger than this maximum value, then the raw data is not set and the function returns false.

Change advertising raw data setting

---

src/utility/ATT.h

This patch will allow to define different ATT_MAX_PEERS according to the used core:
- in platforms that use ArduinoCore-mbed, ATT_MAX_PEERS will be defined by DM_CONN_MAX ([here](https://github.com/arduino/ArduinoCore-mbed/pull/82) set to be equal to 5);
- in platforms that use ArduinoCore-avr (Uno WiFi Rev2), ATT_MAX_PEERS = 3;
- in platforms that use ArduinoCore-samd (MKR WiFi 1010), ATT_MAX_PEERS = 8.

Adjust ATT_MAX_PEERS definition and increase max number of BLE connections for MKR WiFi 1010

---

src/utility/HCICordioTransport.cpp

'NRFCordioHCIDriver::start_reset_sequence()' exploits the ble HOST stack of cordio. This is used to send a reset command to the controller.
ArduinoBLE doesn't use the cordio host stack and already sends a reset command to the controller during the initialization of the library.

Cordio: remove call to reset sequence

---

src/utility/HCICordioTransport.cpp

This PR addresses the namespace changes on mbed-os (cordio and vendor removed).
It also addresses the problem of having mbed macro not considered during the compilation of the cordio thread. It solves this by including the mbed file headers (in this case `<driver/CordioHCITransportDriver.h>`) after `Arduino.h`

Adapt library to mbed-os 6.4.0

---

src/local/BLELocalAttribute.h
src/utility/ATT.cpp

Before this fix, if the `ATT information request` was called on an handle belonging to a non-descriptor attribute, then the response would contain the uuid of the actual attribute's type but with the format of the attribute uuid (0x01 for 16 bit length, 0x02 for 128 bit length).
So, for instance, if the info request was performed on an handle belonging to a service with a uuid of 128 bit, then the response would have been malformed because the size of the attribute's type is 16 bit.
From issue discovered by @ThomasGerstenberg 
https://github.com/arduino-libraries/ArduinoBLE/issues/147

Fix find info resp when called on non-descriptor attributes

---

src/BLECharacteristic.cpp
src/BLECharacteristic.h
src/remote/BLERemoteCharacteristic.cpp
src/remote/BLERemoteCharacteristic.h

When a characteristic is declared (Write | WriteWithoutResponse) the code always creates a request
and expects a response.
By setting withResponse=false the user can bypass the request and write a responseless command.
Reworks and supersedes https://github.com/arduino-libraries/ArduinoBLE/pull/72

Overload writeValue to allow forced write without response

---

.github/workflows/compile-examples.yml

- Use latest releases of GitHub Actions actions in sketch compilation CI workflow (https://github.com/arduino-libraries/ArduinoBLE/commit/425e62d6cd1becc0da188850ca1c2eacc7f0c9e1, https://github.com/arduino-libraries/ArduinoBLE/commit/3f706db4d6496047c38ead5c78e5eac2119a64b2)
- Fix formatting of workflow (https://github.com/arduino-libraries/ArduinoBLE/commit/07965268a6cd5b4945fc212e850ae7038ae933d2, https://github.com/arduino-libraries/ArduinoBLE/commit/489830abebfa5b7fffe8f60464af9a084934dd3c)

Update GitHub Actions workflows and action versions

---

examples/Peripheral/ButtonLED/ButtonLED.ino
src/BLETypedCharacteristics.h
src/utility/ATT.cpp

Hi @sandeepmistry 
I think it should be fine to use standard bool instead boolean as mentioned here:
https://github.com/arduino/Arduino/issues/4673
BR

Replace boolean with standard bool

---

src/utility/HCI.cpp

I find that when I use my nano 33 ble with this BLE lib.
Sometimes when I use the demo project ScanCallback.ino,
my program freezes because of the overflow of _recvBuffer.

fix potential arrary overflow problem of _recvBuffer

---

src/BLEDevice.cpp
src/BLEDevice.h

based on https://github.com/arduino-libraries/ArduinoBLE/pull/150/files and https://github.com/arduino-libraries/ArduinoBLE/pull/162/files
- enables retrieval of remote advertising data 
- enables retrieval of remote manufacturer data
It needs to be tested
@manchoz

Adv data retrieve

---

examples/Peripheral/Advertising/EnhancedAdvertising/EnhancedAdvertising.ino
examples/Peripheral/Advertising/RawDataAdvertising/RawDataAdvertising.ino

While the old way of preparing advertising data is still supported, an alternative enhanced method to build advertising packets is now available.
It consists in defining and configuring an object of type 'BLEAdvertisingData' to build the desired packet.
When it has been configured, by setting the appropriate parameters, it can be used to populate the advertising data packet or the scan response data packet.
Following this way, the user can decide in which packet each parameter should be put.
Also, it is now possible to configure an advertising packet (advertising or scan response) by passing a raw data packet.
If an advertising packet has a raw data parameter set, all its other parameters will be ignored.
Also, advertising parameters such as manufacturer data, service data or raw data …

Add enhanced advertising examples

---

src/BLECharacteristic.cpp
src/BLEDescriptor.cpp
src/BLEService.cpp
src/local/BLELocalCharacteristic.cpp
src/local/BLELocalService.cpp
src/remote/BLERemoteCharacteristic.cpp
src/remote/BLERemoteDevice.cpp
src/remote/BLERemoteService.cpp
src/utility/GATT.cpp
src/utility/HCICordioTransport.cpp

This pull request addresses the issue described in #192 caused by variables initialized in begin() not being deleted in end(). This leads to hangs and crashes reported also in other issues.

Bugfix: memory leak caused by variables not being deleted in end()

---

src/utility/ATT.cpp
src/utility/HCI.cpp
src/utility/HCI.h

Very small change to get rid of compiler warnings. It also shrunk my program by 16850 bytes which is a nice benefit.

Change non returning functions to void + spelling

---

src/utility/BLEUuid.cpp

[BLEDevice::discoverService](https://github.com/stm32duino/STM32duinoBLE/blob/061ec8e7902ab1754a65264787f704d4bb265766/src/BLEDevice.cpp#L205) execute `ATT.discoverAttributes(_addressType, _address, NULL)` passing NULL as 3rd argument, that is eventually passed to [BLEUuid constructor](https://github.com/stm32duino/STM32duinoBLE/blob/061ec8e7902ab1754a65264787f704d4bb265766/src/utility/BLEUuid.cpp#L33) where it is used in `strlen(str)`.
Since dereferencing null pointer is UB, we should avoid to call `strlen(len)`.

Fix hard fault when str is NULL

---

src/BLEService.cpp
src/BLEService.h
src/local/BLELocalAttribute.cpp
src/local/BLELocalAttribute.h
src/local/BLELocalCharacteristic.cpp
src/local/BLELocalService.cpp
src/local/BLELocalService.h
src/utility/GATT.cpp
src/utility/GATT.h

Should fix #243 and maybe some other memory related issues.
Only tested in Peripheral mode, with services and characteristics allocated:
* as global objects (arduino way)
* in function stack
* in heap
On mbed-enabled platforms, the memory check can be activated via
```
....
mbed_stats_heap_t heap_stats;
mbed_stats_heap_get(&heap_stats);
Serial.print("Heap size: ");
Serial.print(heap_stats.current_size);
Serial.print(" / ");
Serial.println(heap_stats.reserved_size);
....
```

Fix memory leak on end() -> begin() -> end()

---

library.properties
src/local/BLELocalDevice.cpp
src/utility/HCICordioTransport.cpp
src/utility/HCIUartTransport.cpp

Add support for Arduino OPTA WiFi (AFX00002)

Add support for OPTA

---

src/BLECharacteristic.cpp
src/BLEDevice.cpp
src/BLEService.cpp
src/utility/ATT.cpp
src/utility/HCISilabsTransport.cpp
src/utility/HCISilabsTransport.h
src/utility/HCIUartTransport.cpp

This PR introduces compatibility for the ArduinoBLE library with Silicon Labs boards using the [Silicon Labs Arduino core](https://github.com/SiliconLabs/arduino).
It is not compatible with core version 2.0.0 but will be compatible in the next core release.

Add support for Silicon Labs board

---

src/local/BLELocalDevice.cpp

The `_advertisingData` and `_scanResponseData` structure are never cleared even if the user call the `BLE.end()`. 
If the user after a BLE.end() opens again the BLE.begin() and confgure local name, service, characteristic, etc. some of them are not set properly since the counters and the data pointers are full from the previous iteration.
With this PR the clear method of `_advertisingData` and `_scanResponseData` is called inside the `BLE.end()` method.

Clear advertising data when BLE end is called

---

src/utility/ATT.cpp

This PR solves the issue of crashes and hangs on M0 board when assigning the variable `uint16_t handle` in the methods `ATTClass::readOrReadBlobReq` and `ATTClass::writeReqOrCmd` as reported also [here](https://github.com/arduino-libraries/ArduinoBLE/pull/316).
The problem was identified, also, trying to write a characteristic exposed by Arduino Nano RP2040 and Arduino MKR1010 from other Arduino boards.

Arduino M0 board crashes when setting BLE handle from data buffer

---

src/utility/HCI.cpp
src/utility/L2CAPSignaling.cpp
src/utility/btct.cpp

```log
src/utility/L2CAPSignaling.cpp: In member function 'virtual void L2CAPSignalingClass::handleSecurityData(uint16_t, uint8_t, uint8_t*)':
src/utility/L2CAPSignaling.cpp:315:5: warning: missing initializer for member 'L2CAPSignalingClass::handleSecurityData(uint16_t, uint8_t, uint8_t*)::GenerateDHKeyCommand::y' [-Wmissing-field-initializers]
315 |     };
|     ^
src/utility/L2CAPSignaling.cpp:116:81: warning: unused parameter 'dlen' [-Wunused-parameter]
116 | void L2CAPSignalingClass::handleSecurityData(uint16_t connectionHandle, uint8_t dlen, uint8_t data[])
|                                                                         ~~~~~~~~^~~~
src/utility/L2CAPSignaling.cpp: In member function 'virtual void L2CAPSignalingClass::smCalculateLTKandConfirm(uint16_t, uint8_t*)': …
```

fix: signed and init field warnings

---

src/utility/HCICordioTransport.cpp

On portenta based board, if the user sketch starts and stops BLE several time, after the first time, the BLE stack advertises the wrong BLE mac address ( "AA:AA:AA:AA:AA:AA" ). This is caused because the BLE.end() function of ArduinoBLE doesn't turn off correctly the BLE mbed-os library.
Here a sketch for reproducing the bug.
```
REDIRECT_STDOUT_TO(Serial);
BLEService ledService("19B10000-E8F2-537E-4F6C-D104768A1214"); // Bluetooth® Low Energy LED Service
// Bluetooth® Low Energy LED Switch Characteristic - custom 128-bit UUID, read and writable by central
BLEByteCharacteristic switchCharacteristic("19B10001-E8F2-537E-4F6C-D104768A1214", BLERead | BLEWrite);
bool turnedOn = false;
const int ledPin = LED_BUILTIN; // pin to use for the LED
uint32_t lastChange = 0; …
```

Fix for BLE restart after a BLE end on portenta based devices

---

src/utility/ATT.cpp

If the peripheral sketch with a subscribeable characteristic closes the connection with the central calling the `BLE.disconnect()` all subsequent subscriptions, after the first connection, are not notified and the characteristic stays always as "subscribed".
In this PR the characteristic CCCD value is cleared when the BLE.disconnect() is called for resetting the characteristic subscription status and allowing new subscriptions.
**Central**
```c++
void setup() {
Serial.begin(9600);
while (!Serial);
// initialize the Bluetooth® Low Energy hardware
BLE.begin();
BLE.scanForUuid("19B10000-E8F2-537E-4F6C-D104768A1214");
}
void loop() {
// put your main code here, to run repeatedly:
BLEDevice peripheral = BLE.available();
if (peripheral) {
// discovered a peripheral, …
```

Clear characteristic cccd value when disconnect

---

src/utility/L2CAPSignaling.cpp

Now correctly acceses the existing variables and uses an unsigned int for size comparison
fixes #355

fix: compilation error when using _BLE_TRACE

---

docs/api.md

BLECharacteristic(uuid, properties, value, valueSize) doesn't exist in source. instead the correct contructor is
BLECharacteristic(uuid, properties, valueSize, fixedLength), where fixedLength has the default value false. Docs have to be adapted accordingly.

Update docs for BLECharacteristic constructor

---

extras/test/CMakeLists.txt
extras/test/src/test_characteristic/test_writeValue.cpp
src/local/BLELocalCharacteristic.cpp
src/utility/ATT.cpp
src/utility/ATT.h

Alternative version of #371 
@fabik111

Make writeValue return the number of bytes written

---

src/utility/HCI.cpp
src/utility/HCICordioTransport.cpp
src/utility/HCICordioTransport.h
src/utility/HCITransport.h

Sometimes my BLE connections to my nrf52840 randomly stopped working. I've noticed that with `BLE.debug(Serial)` the HCI transport returned truncated packets in these situations. I suspect that this issue might be caused by concurrent access to the rx buffer in the cordio HCI transport. The Arduino core seems to use critical section locks [while interacting with the ring buffers](https://github.com/arduino/ArduinoCore-mbed/blob/1302d80a4c1e770460132c76a280388bf44fe153/cores/arduino/Serial.cpp#L176-L178).
This MR introduces a `lockForRead` and `unlockForRead` method on the HCITransport to aquire a critical section lock. A Mutex might make more sense, but requires additional build flags and might not be available if `handleRxData` is called from an interrupt handler.
I've considered the …

Use locks to prevent race conditions in HCICordioTransport

---

library.properties
src/local/BLELocalDevice.cpp
src/utility/HCIUartTransport.cpp
src/utility/HCIVirtualTransportZephyr.cpp
src/utility/HCIVirtualTransportZephyr.h

GIGA R1 WiFi :heavy_check_mark: 
Portenta C33 :heavy_check_mark: 
OPTA :heavy_check_mark: 
Portenta H7 :heavy_check_mark: 
Nano 33 BLE Sense :heavy_check_mark:

Add Zephyr support.
